name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create required directories
        run: |
          mkdir -p models

      - name: Train model
        run: |
          python scripts/train.py

      - name: Run Flask app and test
        run: |
          # Start the Flask app in the background
          nohup python app.py > flask.log 2>&1 &
          sleep 5  # Wait for the app to start

          # Test the Flask app
          curl -X POST http://localhost:5000/predict \
            -H "Content-Type: application/json" \
            -d '{"input": [2000, 3]}'

          # Stop the Flask app
          pkill -f "python app.py"
